### PR TITLE
12148 style

### PR DESCRIPTION
**Pull request by josh-mckenzie**
See: https://issues.apache.org/jira/browse/CASSANDRA-12148

### CODE REVIEW

**Comment by spodkowinski** [comment]
The jira is already committed. What's the status of this PR @josh-mckenzie ?

**Comment by josh-mckenzie** [comment]
Could have sworn we merged in the tests for the 12148 changes. @ptnapoleon - any ideas on this? This PR was for a branch that migrated from Jim's ownership to me and then 12148 sat for months so I wouldn't be surprised for something like this to slip through the cracks.

**Comment by ptnapoleon** [comment]
Grepping through the codebase and the git log, this has not been merged elsewhere.

**Comment by spodkowinski** [comment]
I'm still seeing related failures in dtest results
/ping @josh-mckenzie @ptnapoleon

**Comment by josh-mckenzie** [comment]
Taking a look @spodkowinski. Local env is being a bitch thanks to 2.7 + 3.5 on same host, win w/linux subsystem, but when I finally get the damned setup working I'll get on this.

Sorry about the delay.

**Comment by ptnapoleon** [comment]
I'm not yet familiar with pytest and I know nothing about CDC, but this all looks legitimate. +1

**Comment by josh-mckenzie** [comment]
Right, operating under the assumption that Jim's initial logic (that I reviewed back then) is accurate. This is more a "style sanity check" thing.

**Comment by josh-mckenzie** [comment]
Getting a 403 on push to the apache dtest repo. What's the word there re: access rights @ptnapoleon ?

**Comment by jeffjirsa** [comment]
Should be same group as Cassandra committers - make sure you’re pointing at asf git with https endpoint, not GitHub, etc.

**Comment by josh-mckenzie** [comment]
Ah - that was it @jeffjirsa. Should have realized I was pointed to github on the remote instead of ASF.

[Pushed](https://git-wip-us.apache.org/repos/asf?p=cassandra-dtest.git;a=commit;h=19a17fa90c1156ce1306e459249d67b759cb0f01), closing PR.

**Comment by spodkowinski** [comment]
This seems to break builds.apache.org as the nose imports fail to resolve. I think we moved to pytest for that. 
https://builds.apache.org/view/A-D/view/Cassandra/job/Cassandra-devbranch-dtest/493/console

**Comment by spodkowinski** [comment]
Should now be fixed in 3d0d0f45f56be3e4278a3bcfae763c052bf65dc7

**Comment by josh-mckenzie** [comment]
Interesting. Though we moved to pytest, I'd assumed we still had nose available. Thanks for fixing that!

**Pull request closed without merging**
