### PR TITLE
Fix flake8 violations (so travis and circleci pass)

### PR DESCRIPTION
**Pull request by michaelsembwever**
I've also added ignores for E999 and F821 violations (errors and unrecognised annotations) for no other reason than i couldn't (didn't know how to) fix them.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
@ptnapoleon @ifesdjeen

**Comment by michaelsembwever** [comment]
DTest run against trunk: https://builds.apache.org/view/A-D/view/Cassandra/job/Cassandra-devbranch-dtest/633/

**Comment by mshuler** [comment]
The dtest run linked above failed to run at all, so I think that would be the first thing to fix up.

**Comment by michaelsembwever** [comment]
> The dtest run linked above failed to run at all, so I think that would be the first thing to fix up.

Yeah, mea culpa a bit clumsy of me there…

Also rebased off master.

**Comment by michaelsembwever** [comment]
DTest run against trunk: https://builds.apache.org/view/A-D/view/Cassandra/job/Cassandra-devbranch-dtest/633/

**Pull request closed without merging**
