### PR TITLE
Add a test that non-cdc segments are deleted after replay

### PR DESCRIPTION
**Pull request by shichao-an**
Test that non-cdc segment files generated in previous runs are deleted
after replay.

### CODE REVIEW

**Comment by josh-mckenzie** [comment]
+1. @ptnapoleon - I don't appear to have merge rights on this repo.

**Comment by ptnapoleon** [comment]
I'm sure you do. Do you still want me to commit this?

**Comment by josh-mckenzie** [comment]
See the JIRA. Didn't realize we were in same boat w/inability to merge PR's and this being a mirror of official ASF git.

If you have a few spare cycles to merge this in, feel free. I'm pretty slammed atm.

**Comment by ptnapoleon** [comment]
Committed.

**Pull request closed without merging**
